
name: "Build Preview Deployment"
permissions:
  contents: write
on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Install Yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 22
      - name: Install D2
        run: "curl -fsSL https://d2lang.com/install.sh | sh -s --"
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Build Docs
        run: |
          python main.py
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
